version: '3.8'

services:
  app-dev:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: app-dev
    volumes:
      - ../:/opt/app
    init: true
    restart: on-failure
    ports:
      - ${PORT}:4000
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    init: true
    restart: on-failure
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
