version: '3'

services:
  app:
    build:
      context: ../build
    container_name: camara-deputados_graphql_app
    init: true
    restart: on-failure
    ports:
      - 3000:3000

  redis:
    image: redis
    container_name: camara-deputados_graphql_redis
    init: true
    restart: on-failure
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
