name: dependabot-yarn2-autofix

on:
  push:
    branches: [ dependabot/npm_and_yarn/** ]
  pull_request:
    branches: [ dependabot/npm_and_yarn/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Git Config
        run: |
          git config --global user.name '${{ github.event.commits[0].author.name }}'
          git config --global user.email '${{ github.event.commits[0].author.email }}'

      - name: Get Last Commit
        run: |
          echo "PRIOR_COMMIT=$(git log -1 --pretty=format:"%s")" >> $GITHUB_ENV

      - name: Rollback yarn.lock
        run: |
          git checkout $(git log -n1 --skip 1 --oneline yarn.lock | awk '{print $1;}') -- yarn.lock
          yarn

      - name: Deps Autofix
        run: |
          echo "Prior commit is: ${{ env.PRIOR_COMMIT }}"

          PKG=$(yarn dependabot:utils pkg --title ${{ env.PRIOR_COMMIT }})
          FROM=$(yarn dependabot:utils from --title ${{ env.PRIOR_COMMIT }})
          TO=$(yarn dependabot:utils to --title ${{ env.PRIOR_COMMIT }})
          TYPE_AND_SCOPE=$(yarn dependabot:utils type-and-scope --title ${{ env.PRIOR_COMMIT }})

          echo "Update will be: $PKG from $FROM to $TO"

          yarn up $PKG $FROM@$^$TO
          yarn

          git add yarn.lock package.json
          git commit -m "$TYPE_AND_SCOPE: fix bump $PKG from $FROM to $TO"
          git push
